// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBckKKCF7awJbj90j6GDnpnOR3GyaPrwh8',
    appId: '1:164137632599:web:6412ba619c49624c71f412',
    messagingSenderId: '164137632599',
    projectId: 'chatapp-flutter-6437c',
    authDomain: 'chatapp-flutter-6437c.firebaseapp.com',
    storageBucket: 'chatapp-flutter-6437c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHCoeje-XLt17nyn4UTgmQfZ18kqdemmY',
    appId: '1:164137632599:android:b097396c1666803671f412',
    messagingSenderId: '164137632599',
    projectId: 'chatapp-flutter-6437c',
    storageBucket: 'chatapp-flutter-6437c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjrMsXtCkANNHPWy1W3Fug7qL06_TSvvE',
    appId: '1:164137632599:ios:7d574b60c670ee6971f412',
    messagingSenderId: '164137632599',
    projectId: 'chatapp-flutter-6437c',
    storageBucket: 'chatapp-flutter-6437c.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
